version: '3'

secrets:
  db_password:
    file: db_password.txt

networks:
  frontend:
  backend:

services:
  productservice:
    build: product-service
    volumes:
      - "./config:/config"
      - "./product-service/src:/code"
    secrets:
      - db_password
    networks:
      - frontend
      - backend
    ports:
      - "5678:5678"
    environment:
      - DEBUG=True
    depends_on:
      - db

  web:
    build: nginx
    ports:
      - "80:80"
    networks:
      - frontend
    depends_on:
      - productservice

  db:
    image: mysql
    command: "--init-file /data/application/init.sql --default-authentication-plugin=mysql_native_password"
    volumes:
      - "./db/init.sql:/data/application/init.sql"
      - "db-volume:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$password"]
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  db-volume:
